/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppMarketsRouteImport } from './routes/app.markets'
import { Route as AppNewExpansionRouteImport } from './routes/app.new-expansion'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppAgentsAgentIdRouteImport } from './routes/app.agents.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppNewExpansionRoute = AppNewExpansionRouteImport.update({
  id: '/new-expansion',
  path: '/new-expansion',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/new-expansion': typeof AppNewExpansionRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/plan': typeof AppPlanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/new-expansion': typeof AppNewExpansionRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/plan': typeof AppPlanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/new-expansion': typeof AppNewExpansionRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/plan': typeof AppPlanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/campaigns'
    | '/app/knowledge'
    | '/app/markets'
    | '/app/new-expansion'
    | '/app/opportunities'
    | '/app/orders'
    | '/app/plan'
    | '/app/settings'
    | '/app/'
    | '/app/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analytics'
    | '/app/campaigns'
    | '/app/knowledge'
    | '/app/markets'
    | '/app/new-expansion'
    | '/app/opportunities'
    | '/app/orders'
    | '/app/plan'
    | '/app/settings'
    | '/app'
    | '/app/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/campaigns'
    | '/app/knowledge'
    | '/app/markets'
    | '/app/new-expansion'
    | '/app/opportunities'
    | '/app/orders'
    | '/app/plan'
    | '/app/settings'
    | '/app/'
    | '/app/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/markets': {
      id: '/app/markets'
      path: '/markets'
      fullPath: '/app/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new-expansion': {
      id: '/app/new-expansion'
      path: '/new-expansion'
      fullPath: '/app/new-expansion'
      preLoaderRoute: typeof AppNewExpansionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents/$agentId': {
      id: '/app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/app/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppNewExpansionRoute: typeof AppNewExpansionRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppNewExpansionRoute: AppNewExpansionRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPlanRoute: AppPlanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
